import traci
import random
from sumolib import checkBinary
import subprocess
import sys
import os

class Sumo:

    def __init__(self, config):
        
        self.sumoBinary = checkBinary('sumo-gui')
        self.max_time = 0
         
        self.config = config
        self.refdist = 0.0
        self.edges = [] 
        self.streets = set()       

        # Fix random seed for reproducibility
        random.seed(int(self.config["seed"]))
        pass

    def run(self): 

        #Control
        self.uptime()
        self.generate_activity_trips()
        self.apply_fleet_conversion()
        self.startSim()

        #Surface
        self.up_streets()
        self.streetslist = list(self.streets)
        self.reference_length()

        return
    
    def uptime(self):
        self.max_time = self.config["Max_time"]
        return self.max_time
    
    def generate_activity_trips(self):
        
        # activitygen is usually located in the same directory as SUMO
        # If 'activitygen' is not in the PATH, use the full path
        activitygen_bin = "activitygen" 

        cmd = [
            activitygen_bin,
            "--net-file", self.config["net-file"],
            "--stat-file",  self.config["stat"], 
            "--output-file", self.config["route-files"],
            "--random", 
            "--seed", "42"
        ]
        
        try:
            print(f"Executing: {' '.join(cmd)}")
            subprocess.run(cmd, check=True)
            print("✓ Activity-based routes generated successfully!")
        except subprocess.CalledProcessError as e:
            print(f"Error while executing activitygen: {e}")
        except FileNotFoundError:
            print("Error: 'activitygen' executable not found in PATH.")

    def apply_fleet_conversion(self):
        """
        Executes the fleet conversion script (mixed/electric)
        using the path defined in the config dictionary.
        """
        # 1. Retrieves the path from the config dictionary

        script_path = self.config["convert-fleet"]

        # 2. Builds the command using the current Python executable
        # This ensures that libraries such as 'random' and 'os' work correctly
        cmd = [sys.executable, script_path]

        try:
            # Checks if the file exists before attempting to run it
            if not os.path.exists(script_path):
                print(f"Error: Conversion script not found at: {script_path}")
                return

            print(f"Executing fleet conversion: {' '.join(cmd)}")
            
            # Executes the script. 'capture_output=True' allows reading what the script printed (counters)
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            
            # Prints the summary (how many cars/buses were converted) generated by the script
            print(result.stdout)
            print("✓ Fleet successfully converted to mixed!")

        except subprocess.CalledProcessError as e:
            print(f"Error while executing conversion script: {e}")
            if e.stderr:
                print(f"Error details: {e.stderr}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

    #Starts the simulation
    def startSim(self):
        traci.start(
            [
                self.sumoBinary,
                '--net-file', self.config["net-file"],
                '--route-files', self.config["route-mista"],
                '--additional-files', self.config["additional-files"],
                '--step-length', self.config["step"], 
                '--delay', self.config["delay"],
                '--statistic-output', self.config["statistic-output"],
                '--duration-log.statistics', 'true',
                '--tripinfo-output', self.config["tripinfo-output"],
                '--gui-settings-file', self.config["gui-settings-file"],
                '--seed', self.config["seed"],
                '--time-to-teleport', self.config["time-to-teleport"],   
                '--start',      
                '--quit-on-end' 
            ]
        )
    
    # Advance the simulation
    def step(self):
        traci.simulationStep()
        return
    
    def up_streets(self):
        self.edges = traci.edge.getIDList()

        for edge in self.edges:
            if not edge.startswith(":"):  # ignore internal edges 
                self.streets.add(edge.split("_")[0])
        return
    
    def reference_length(self):
        
        start = random.choice(self.streetslist)
        
        far_edge, _ = self.farthest_from(start)

        _, self.refdist = self.farthest_from(far_edge)
        
        return self.refdist

    def farthest_from(self,source_edge):
        max_dist = 0.0
        farthest_edge = source_edge

        for target_edge in self.streetslist:
            try:
                dist = traci.simulation.getDistanceRoad(
                    source_edge, 0,
                    target_edge, 0,
                    isDriving=True
                )
                if dist > max_dist:
                    max_dist = dist
                    farthest_edge = target_edge
            except:
                continue

        return farthest_edge, max_dist
