import random  # Library for random number generation
import os      # Library for file and directory handling
import json

# Fix random seed for reproducibility
random.seed(42)

"""Load config from config/config.json"""
with open(r'config/config.json', 'r') as config_file:
    config = json.load(config_file)

# =============================================================================
# FLEET CONFIGURATION (Adjust values as needed)
# =============================================================================

# Define the percentage of vehicles to convert (0.30 = 30%)
PROB_ELECTRIC_CAR = 0.30   # 30% of cars will be electric
PROB_ELECTRIC_BUS = 0.10   # 10% of buses will be electric

# File names (must be in the same directory or correctly referenced)
# 'INPUT_FILE' should be the file generated by Activitygen
INPUT_FILE  = config["route-files"]
OUTPUT_FILE = config["route-mista"]


def main():

    # 1. Check if input file exists to avoid errors
    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: File '{INPUT_FILE}' was not found.")
        print("Generate the file with Activitygen before running this script.")
        return

    print(f"Processing '{INPUT_FILE}'...")

    # Counters for reporting
    electric_car_count = 0
    electric_bus_count = 0
    total_vehicles = 0

    # 2. Open input file (read) and output file (write)
    with open(INPUT_FILE, "r", encoding="utf-8") as f_in, \
         open(OUTPUT_FILE, "w", encoding="utf-8") as f_out:
        
        # 3. Read file line by line
        for line in f_in:
            
            number = random.random()

            if number <= PROB_ELECTRIC_BUS:
                line = line.replace('type="random"', 'type="ElectricBus" color="255,255,0"')
                electric_bus_count += 1
                total_vehicles += 1

            elif PROB_ELECTRIC_BUS < number <= PROB_ELECTRIC_CAR:
                line = line.replace('type="random"', 'type="evehicle" color="255,255,0"')
                electric_car_count += 1
                total_vehicles += 1

            else:
                total_vehicles += 1
                line = line.replace('type="random"', 'type="random" color="255,255,255"')
            
            f_out.write(line)

    # 5. Print summary
    print("-" * 50)
    print("CONVERSION COMPLETED!")
    print(f"Total vehicles processed: {total_vehicles}")
    print(f"Electric cars created:   {electric_car_count}")
    print(f"Electric buses created:  {electric_bus_count}")
    print(f"Output file saved as:    {OUTPUT_FILE}")
    print("-" * 50)


# Script entry point
if __name__ == "__main__":
    main()